remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "G2 Quantix"
description: "Innovating at biotech’s data and AI frontier"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://www.g2quantix.com"
logo: "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: # 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: welcomege-ml-github
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
Gary:
  name: Gary
  picture: /images/avatar.png
  email: info@g2quantix.com

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/company/g2quantix/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/G2Quantix
    icon: fab fa-github

copyright: "G2 Quantix Solutions L.L.C. 2025"
